IMG = {
    "dashboard": "https://images.unsplash.com/photo-1526628953301-3e589a6a8b74?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1MDZ8MHwxfHNlYXJjaHwyfHxkYXJrJTIwZW50ZXJwcmlzZSUyMGFpJTIwdGVjaG5vbG9neSUyMGRhc2hib2FyZHxlbnwwfHx8fDE3ODE4ODcxNTB8MA&ixlib=rb-4.1.0&q=85",
    "analytics": "https://images.unsplash.com/photo-1686061592689-312bbfb5c055?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1MDZ8MHwxfHNlYXJjaHwzfHxkYXJrJTIwZW50ZXJwcmlzZSUyMGFpJTIwdGVjaG5vbG9neSUyMGRhc2hib2FyZHxlbnwwfHx8fDE3ODE4ODcxNTB8MA&ixlib=rb-4.1.0&q=85",
    "metrics": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1MDZ8MHwxfHNlYXJjaHwxfHxkYXJrJTIwZW50ZXJwcmlzZSUyMGFpJTIwdGVjaG5vbG9neSUyMGRhc2hib2FyZHxlbnwwfHx8fDE3ODE4ODcxNTB8MA&ixlib=rb-4.1.0&q=85",
    "chatgpt": "https://images.pexels.com/photos/16027824/pexels-photo-16027824.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "aichat": "https://images.pexels.com/photos/30530402/pexels-photo-30530402.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "notion": "https://images.unsplash.com/photo-1507099985932-87a4520ed1d5?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDk1ODF8MHwxfHNlYXJjaHwxfHxwcm9kdWN0aXZpdHklMjB0ZW1wbGF0ZSUyMG5vdGlvbnxlbnwwfHx8fDE3ODQyOTg3Mzd8MA&ixlib=rb-4.1.0&q=85",
    "book": "https://images.unsplash.com/photo-1542123491-63f422a5f45e?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDk1ODF8MHwxfHNlYXJjaHwzfHxwcm9kdWN0aXZpdHklMjB0ZW1wbGF0ZSUyMG5vdGlvbnxlbnwwfHx8fDE3ODQyOTg3Mzd8MA&ixlib=rb-4.1.0&q=85",
    "workflow": "https://images.unsplash.com/photo-1743385779347-1549dabf1320?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDk1ODF8MHwxfHNlYXJjaHwyfHxwcm9kdWN0aXZpdHklMjB0ZW1wbGF0ZSUyMG5vdGlvbnxlbnwwfHx8fDE3ODQyOTg3Mzd8MA&ixlib=rb-4.1.0&q=85",
    "code": "https://images.unsplash.com/photo-1759661881353-5b9cc55e1cf4?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTY2NzB8MHwxfHNlYXJjaHwyfHxkZXZlbG9wZXIlMjBjb2RpbmclMjBhYnN0cmFjdCUyMG5lb258ZW58MHx8fHwxNzgyNDY4NTE4fDA&ixlib=rb-4.1.0&q=85",
    "neon": "https://images.unsplash.com/photo-1588007374946-c79543903e8a?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTY2NzB8MHwxfHNlYXJjaHwxfHxkZXZlbG9wZXIlMjBjb2RpbmclMjBhYnN0cmFjdCUyMG5lb258ZW58MHx8fHwxNzgyNDY4NTE4fDA&ixlib=rb-4.1.0&q=85",
    "cyber": "https://images.pexels.com/photos/8134609/pexels-photo-8134609.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "matrix": "https://images.pexels.com/photos/97077/pexels-photo-97077.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
}

SEED_CATEGORIES = [
    {"name": "Automações", "slug": "automacoes", "icon": "workflow", "description": "Fluxos e automações prontas para escalar sua operação."},
    {"name": "Templates", "slug": "templates", "icon": "layout-template", "description": "Modelos prontos de Notion, planilhas e documentos."},
    {"name": "Ferramentas IA", "slug": "ferramentas-ia", "icon": "sparkles", "description": "Ferramentas potencializadas por inteligência artificial."},
    {"name": "Skills Claude", "slug": "skills-claude", "icon": "terminal", "description": "Comandos e prompts avançados para Claude."},
    {"name": "Cursos & Ebooks", "slug": "cursos-ebooks", "icon": "graduation-cap", "description": "Materiais educacionais e guias completos."},
]

SEED_PRODUCTS = [
    {"title": "AI Dashboard Kit Pro", "cat_slug": "ferramentas-ia", "type": "paid", "price": 197.0,
     "short_description": "Dashboard analítico com IA para monitorar métricas em tempo real.",
     "description": "Kit completo de dashboard analítico com integração de IA. Inclui componentes prontos, gráficos interativos, alertas inteligentes e templates de relatórios automatizados. Ideal para times de dados e growth.",
     "thumbnail": IMG["dashboard"], "tags": ["dashboard", "analytics", "ia"], "featured": True,
     "checkout_url": "https://kiwify.com.br/checkout/ai-dashboard", "views": 340, "downloads": 0},
    {"title": "Automação de Leads no WhatsApp", "cat_slug": "automacoes", "type": "paid", "price": 147.0,
     "short_description": "Fluxo completo de qualificação e nutrição de leads via WhatsApp.",
     "description": "Automação pronta para capturar, qualificar e nutrir leads no WhatsApp usando Twilio. Inclui árvore de decisão, mensagens templates e integração com CRM.",
     "thumbnail": IMG["analytics"], "tags": ["whatsapp", "leads", "automacao"], "featured": True,
     "checkout_url": "https://kiwify.com.br/checkout/whats-leads", "views": 210, "downloads": 0},
    {"title": "Prompt Pack — 100 Prompts de Marketing", "cat_slug": "ferramentas-ia", "type": "free", "price": 0.0,
     "short_description": "Coleção gratuita de 100 prompts testados para marketing e vendas.",
     "description": "Pacote gratuito com 100 prompts prontos para copywriting, anúncios, e-mails e redes sociais. Baixe agora e acelere sua produção de conteúdo com IA.",
     "thumbnail": IMG["chatgpt"], "tags": ["prompts", "marketing", "gratis"], "featured": True,
     "download_url": "https://example.com/downloads/prompt-pack.pdf", "views": 890, "downloads": 320},
    {"title": "Template Notion — Gestão de Projetos", "cat_slug": "templates", "type": "free", "price": 0.0,
     "short_description": "Sistema completo de gestão de projetos no Notion, grátis.",
     "description": "Template gratuito de Notion para gerenciar projetos, tarefas, sprints e OKRs. Estrutura pronta com dashboards, kanban e cronograma.",
     "thumbnail": IMG["notion"], "tags": ["notion", "template", "projetos"], "featured": False,
     "download_url": "https://example.com/downloads/notion-projetos", "views": 640, "downloads": 410},
    {"title": "Planilha Financeira Inteligente", "cat_slug": "templates", "type": "paid", "price": 67.0,
     "short_description": "Planilha automatizada de controle financeiro pessoal e empresarial.",
     "description": "Planilha com fórmulas automatizadas, dashboards visuais e projeções financeiras. Controle fluxo de caixa, categorias e metas em um só lugar.",
     "thumbnail": IMG["metrics"], "tags": ["financas", "planilha", "gestao"], "featured": False,
     "checkout_url": "https://kiwify.com.br/checkout/planilha-financeira", "views": 175, "downloads": 0},
    {"title": "Skills Claude — Pack Desenvolvedor", "cat_slug": "skills-claude", "type": "free", "price": 0.0,
     "short_description": "Comandos avançados de Claude para desenvolvimento de software.",
     "description": "Coletânea gratuita de skills e comandos para acelerar desenvolvimento com Claude: refatoração, debugging, testes e documentação automatizada.",
     "thumbnail": IMG["code"], "tags": ["claude", "dev", "skills"], "featured": True,
     "download_url": "https://example.com/downloads/claude-dev", "views": 520, "downloads": 280},
    {"title": "Agente de IA para Atendimento", "cat_slug": "ferramentas-ia", "type": "paid", "price": 297.0,
     "short_description": "Agente de IA completo para atendimento e suporte automatizado.",
     "description": "Solução completa de agente de IA para atendimento ao cliente 24/7. Integração com WhatsApp, base de conhecimento e escalonamento humano inteligente.",
     "thumbnail": IMG["aichat"], "tags": ["agente", "atendimento", "ia"], "featured": True,
     "checkout_url": "https://kiwify.com.br/checkout/agente-ia", "views": 265, "downloads": 0},
    {"title": "Ebook — Automação de Negócios com IA", "cat_slug": "cursos-ebooks", "type": "free", "price": 0.0,
     "short_description": "Guia gratuito para automatizar processos usando inteligência artificial.",
     "description": "Ebook completo com estratégias práticas para automatizar seu negócio com IA. Casos reais, ferramentas recomendadas e passo a passo de implementação.",
     "thumbnail": IMG["book"], "tags": ["ebook", "automacao", "gratis"], "featured": False,
     "download_url": "https://example.com/downloads/ebook-automacao", "views": 730, "downloads": 495},
    {"title": "Workflow n8n — Integração Total", "cat_slug": "automacoes", "type": "paid", "price": 127.0,
     "short_description": "Workflows n8n prontos para integrar suas ferramentas favoritas.",
     "description": "Biblioteca de workflows n8n prontos para integrar CRM, e-mail, planilhas, WhatsApp e IA. Copie, cole e automatize.",
     "thumbnail": IMG["workflow"], "tags": ["n8n", "integracao", "workflow"], "featured": False,
     "checkout_url": "https://kiwify.com.br/checkout/n8n-workflows", "views": 190, "downloads": 0},
    {"title": "Kit de Cursores & UI Neon", "cat_slug": "templates", "type": "paid", "price": 47.0,
     "short_description": "Componentes UI e cursores animados com estética neon.",
     "description": "Kit de componentes de interface com estética tech neon: botões, cards, cursores animados e microinterações prontas para seu projeto.",
     "thumbnail": IMG["neon"], "tags": ["ui", "design", "neon"], "featured": False,
     "checkout_url": "https://kiwify.com.br/checkout/ui-neon", "views": 120, "downloads": 0},
    {"title": "Guia de Segurança Digital", "cat_slug": "cursos-ebooks", "type": "free", "price": 0.0,
     "short_description": "Manual gratuito de boas práticas de segurança e privacidade.",
     "description": "Guia gratuito com boas práticas de segurança digital, proteção de dados e privacidade para profissionais e empresas.",
     "thumbnail": IMG["cyber"], "tags": ["seguranca", "guia", "gratis"], "featured": False,
     "download_url": "https://example.com/downloads/guia-seguranca", "views": 410, "downloads": 230},
    {"title": "Scraper Inteligente com IA", "cat_slug": "automacoes", "type": "paid", "price": 167.0,
     "short_description": "Ferramenta de scraping com processamento inteligente de dados.",
     "description": "Solução de web scraping potencializada por IA para coletar, estruturar e analisar dados automaticamente. Inclui código e documentação.",
     "thumbnail": IMG["matrix"], "tags": ["scraper", "dados", "ia"], "featured": False,
     "checkout_url": "https://kiwify.com.br/checkout/scraper-ia", "views": 155, "downloads": 0},
]

SEED_SKILLS = [
    {"title": "Refatorar Código", "category": "Desenvolvimento",
     "description": "Peça ao Claude para refatorar mantendo comportamento e melhorando legibilidade.",
     "command": "Refatore este código mantendo o comportamento idêntico. Melhore legibilidade, nomeie variáveis com clareza e adicione tipos onde fizer sentido:\n\n[cole seu código]",
     "tags": ["dev", "refactor"]},
    {"title": "Gerar Testes Unitários", "category": "Desenvolvimento",
     "description": "Crie testes cobrindo casos felizes e de borda.",
     "command": "Gere testes unitários completos para o código abaixo, cobrindo casos de sucesso, erro e borda. Use a biblioteca de testes idiomática da linguagem:\n\n[cole seu código]",
     "tags": ["dev", "testes"]},
    {"title": "Copywriting de Anúncio", "category": "Marketing",
     "description": "Gere variações de copy persuasiva para anúncios.",
     "command": "Escreva 5 variações de copy persuasiva para um anúncio do produto [PRODUTO], público [PÚBLICO], destacando o benefício [BENEFÍCIO]. Tom: [TOM].",
     "tags": ["marketing", "copy"]},
    {"title": "Resumir Documento", "category": "Produtividade",
     "description": "Extraia os pontos-chave de textos longos.",
     "command": "Resuma o texto abaixo em bullet points objetivos, destacando decisões, prazos e responsáveis:\n\n[cole o texto]",
     "tags": ["produtividade", "resumo"]},
    {"title": "Analisar Dados de Planilha", "category": "Dados",
     "description": "Interprete dados e gere insights acionáveis.",
     "command": "Analise os dados abaixo e liste 5 insights acionáveis, tendências e anomalias. Sugira próximos passos:\n\n[cole os dados]",
     "tags": ["dados", "analise"]},
    {"title": "Criar Plano de Conteúdo", "category": "Marketing",
     "description": "Monte um calendário editorial estratégico.",
     "command": "Crie um plano de conteúdo de 30 dias para [NICHO] no [CANAL], com temas, formatos e CTAs alinhados ao objetivo de [OBJETIVO].",
     "tags": ["marketing", "conteudo"]},
    {"title": "Revisar Contrato", "category": "Negócios",
     "description": "Identifique cláusulas de risco em contratos.",
     "command": "Revise o contrato abaixo e aponte cláusulas de risco, ambiguidades e pontos de atenção. Sugira melhorias em linguagem clara:\n\n[cole o contrato]",
     "tags": ["negocios", "juridico"]},
    {"title": "Documentar API", "category": "Desenvolvimento",
     "description": "Gere documentação clara de endpoints.",
     "command": "Gere documentação clara em formato Markdown para os endpoints abaixo, incluindo parâmetros, exemplos de request/response e códigos de erro:\n\n[cole os endpoints]",
     "tags": ["dev", "docs"]},
]

SEED_COMMUNITY = [
    {"name": "Grupo VIP no WhatsApp", "platform": "whatsapp", "url": "https://chat.whatsapp.com/exemplo",
     "description": "Comunidade exclusiva com novidades, drops e suporte.", "icon": "message-circle"},
    {"name": "Canal no Telegram", "platform": "telegram", "url": "https://t.me/exemplo",
     "description": "Avisos rápidos, lançamentos e conteúdos gratuitos.", "icon": "send"},
    {"name": "Comunidade no Discord", "platform": "discord", "url": "https://discord.gg/exemplo",
     "description": "Troque ideias, tire dúvidas e participe de eventos ao vivo.", "icon": "gamepad-2"},
    {"name": "Perfil no Instagram", "platform": "instagram", "url": "https://instagram.com/exemplo",
     "description": "Bastidores, dicas e novidades da marca.", "icon": "instagram"},
    {"name": "Canal no YouTube", "platform": "youtube", "url": "https://youtube.com/@exemplo",
     "description": "Tutoriais, reviews e aulas completas.", "icon": "youtube"},
]

SEED_FAQS = [
    {"question": "Como acesso os produtos gratuitos?", "category": "Acesso",
     "answer": "Basta criar sua conta gratuita, acessar a página do produto e preencher o formulário. O link de download é liberado na hora e também fica salvo em Minha Conta."},
    {"question": "Como funciona a compra de produtos pagos?", "category": "Pagamento",
     "answer": "Ao clicar em comprar, você é redirecionado para nosso checkout seguro externo. Após a confirmação do pagamento, o acesso é liberado e registrado no seu histórico."},
    {"question": "Quais formas de pagamento são aceitas?", "category": "Pagamento",
     "answer": "Aceitamos cartão de crédito, Pix e boleto através da nossa plataforma de checkout. As opções aparecem na tela de pagamento."},
    {"question": "Posso acessar meus produtos depois?", "category": "Acesso",
     "answer": "Sim! Todos os seus downloads e compras ficam salvos permanentemente na área Minha Conta, acessível a qualquer momento."},
    {"question": "O que são as Skills Claude?", "category": "Recursos",
     "answer": "São comandos e prompts avançados prontos para usar com o Claude. Você pode copiar cada comando com um clique e usá-lo diretamente na sua IA."},
    {"question": "Como entro em contato com o suporte?", "category": "Suporte",
     "answer": "Você pode falar conosco pelos canais da Comunidade (WhatsApp, Telegram, Discord) ou usar o assistente de IA disponível no canto da tela."},
    {"question": "Vocês oferecem reembolso?", "category": "Pagamento",
     "answer": "Sim, produtos pagos possuem garantia conforme descrito na página de checkout. Entre em contato com o suporte para solicitar."},
]
