IMG = {
    "dashboard": "https://images.unsplash.com/photo-1526628953301-3e589a6a8b74?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1MDZ8MHwxfHNlYXJjaHwyfHxkYXJrJTIwZW50ZXJwcmlzZSUyMGFpJTIwdGVjaG5vbG9neSUyMGRhc2hib2FyZHxlbnwwfHx8fDE3ODE4ODcxNTB8MA&ixlib=rb-4.1.0&q=85",
    "analytics": "https://images.unsplash.com/photo-1686061592689-312bbfb5c055?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1MDZ8MHwxfHNlYXJjaHwzfHxkYXJrJTIwZW50ZXJwcmlzZSUyMGFpJTIwdGVjaG5vbG9neSUyMGRhc2hib2FyZHxlbnwwfHx8fDE3ODE4ODcxNTB8MA&ixlib=rb-4.1.0&q=85",
    "metrics": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1MDZ8MHwxfHNlYXJjaHwxfHxkYXJrJTIwZW50ZXJwcmlzZSUyMGFpJTIwdGVjaG5vbG9neSUyMGRhc2hib2FyZHxlbnwwfHx8fDE3ODE4ODcxNTB8MA&ixlib=rb-4.1.0&q=85",
    "chatgpt": "https://images.pexels.com/photos/16027824/pexels-photo-16027824.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "aichat": "https://images.pexels.com/photos/30530402/pexels-photo-30530402.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "notion": "https://images.unsplash.com/photo-1507099985932-87a4520ed1d5?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDk1ODF8MHwxfHNlYXJjaHwxfHxwcm9kdWN0aXZpdHklMjB0ZW1wbGF0ZSUyMG5vdGlvbnxlbnwwfHx8fDE3ODQyOTg3Mzd8MA&ixlib=rb-4.1.0&q=85",
    "book": "https://images.unsplash.com/photo-1542123491-63f422a5f45e?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDk1ODF8MHwxfHNlYXJjaHwzfHxwcm9kdWN0aXZpdHklMjB0ZW1wbGF0ZSUyMG5vdGlvbnxlbnwwfHx8fDE3ODQyOTg3Mzd8MA&ixlib=rb-4.1.0&q=85",
    "workflow": "https://images.unsplash.com/photo-1743385779347-1549dabf1320?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDk1ODF8MHwxfHNlYXJjaHwyfHxwcm9kdWN0aXZpdHklMjB0ZW1wbGF0ZSUyMG5vdGlvbnxlbnwwfHx8fDE3ODQyOTg3Mzd8MA&ixlib=rb-4.1.0&q=85",
    "code": "https://images.unsplash.com/photo-1759661881353-5b9cc55e1cf4?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTY2NzB8MHwxfHNlYXJjaHwyfHxkZXZlbG9wZXIlMjBjb2RpbmclMjBhYnN0cmFjdCUyMG5lb258ZW58MHx8fHwxNzgyNDY4NTE4fDA&ixlib=rb-4.1.0&q=85",
    "neon": "https://images.unsplash.com/photo-1588007374946-c79543903e8a?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTY2NzB8MHwxfHNlYXJjaHwxfHxkZXZlbG9wZXIlMjBjb2RpbmclMjBhYnN0cmFjdCUyMG5lb258ZW58MHx8fHwxNzgyNDY4NTE4fDA&ixlib=rb-4.1.0&q=85",
    "cyber": "https://images.pexels.com/photos/8134609/pexels-photo-8134609.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "matrix": "https://images.pexels.com/photos/97077/pexels-photo-97077.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
}

SEED_CATEGORIES = [
    {"name": "Automações", "slug": "automacoes", "icon": "workflow", "description": "Fluxos e automações prontas para escalar sua operação."},
    {"name": "Templates", "slug": "templates", "icon": "layout-template", "description": "Modelos prontos de Notion, planilhas e documentos."},
    {"name": "Ferramentas IA", "slug": "ferramentas-ia", "icon": "sparkles", "description": "Ferramentas potencializadas por inteligência artificial."},
    {"name": "Skills", "slug": "skills-claude", "icon": "terminal", "description": "Comandos e prompts avançados para Claude."},
    {"name": "Cursos & Ebooks", "slug": "cursos-ebooks", "icon": "graduation-cap", "description": "Materiais educacionais e guias completos."},
]

SEED_PRODUCTS = [
    {"title": "AI Dashboard Kit Pro", "cat_slug": "ferramentas-ia", "type": "paid", "price": 197.0,
     "short_description": "Dashboard analítico com IA para monitorar métricas em tempo real.",
     "description": "Kit completo de dashboard analítico com integração de IA. Inclui componentes prontos, gráficos interativos, alertas inteligentes e templates de relatórios automatizados. Ideal para times de dados e growth.",
     "thumbnail": IMG["dashboard"], "tags": ["dashboard", "analytics", "ia"], "featured": True,
     "checkout_url": "https://kiwify.com.br/checkout/ai-dashboard", "views": 340, "downloads": 0},
    {"title": "Automação de Leads no WhatsApp", "cat_slug": "automacoes", "type": "paid", "price": 147.0,
     "short_description": "Fluxo completo de qualificação e nutrição de leads via WhatsApp.",
     "description": "Automação pronta para capturar, qualificar e nutrir leads no WhatsApp usando Twilio. Inclui árvore de decisão, mensagens templates e integração com CRM.",
     "thumbnail": IMG["analytics"], "tags": ["whatsapp", "leads", "automacao"], "featured": True,
     "checkout_url": "https://kiwify.com.br/checkout/whats-leads", "views": 210, "downloads": 0},
    {"title": "Prompt Pack — 100 Prompts de Marketing", "cat_slug": "ferramentas-ia", "type": "free", "price": 0.0,
     "short_description": "Coleção gratuita de 100 prompts testados para marketing e vendas.",
     "description": "Pacote gratuito com 100 prompts prontos para copywriting, anúncios, e-mails e redes sociais. Baixe agora e acelere sua produção de conteúdo com IA.",
     "thumbnail": IMG["chatgpt"], "tags": ["prompts", "marketing", "gratis"], "featured": True,
     "download_url": "https://example.com/downloads/prompt-pack.pdf", "views": 890, "downloads": 320},
    {"title": "Template Notion — Gestão de Projetos", "cat_slug": "templates", "type": "free", "price": 0.0,
     "short_description": "Sistema completo de gestão de projetos no Notion, grátis.",
     "description": "Template gratuito de Notion para gerenciar projetos, tarefas, sprints e OKRs. Estrutura pronta com dashboards, kanban e cronograma.",
     "thumbnail": IMG["notion"], "tags": ["notion", "template", "projetos"], "featured": False,
     "download_url": "https://example.com/downloads/notion-projetos", "views": 640, "downloads": 410},
    {"title": "Planilha Financeira Inteligente", "cat_slug": "templates", "type": "paid", "price": 67.0,
     "short_description": "Planilha automatizada de controle financeiro pessoal e empresarial.",
     "description": "Planilha com fórmulas automatizadas, dashboards visuais e projeções financeiras. Controle fluxo de caixa, categorias e metas em um só lugar.",
     "thumbnail": IMG["metrics"], "tags": ["financas", "planilha", "gestao"], "featured": False,
     "checkout_url": "https://kiwify.com.br/checkout/planilha-financeira", "views": 175, "downloads": 0},
    {"title": "Skills — Pack Desenvolvedor", "cat_slug": "skills-claude", "type": "free", "price": 0.0,
     "short_description": "Comandos avançados de Claude para desenvolvimento de software.",
     "description": "Coletânea gratuita de skills e comandos para acelerar desenvolvimento com Claude: refatoração, debugging, testes e documentação automatizada.",
     "thumbnail": IMG["code"], "tags": ["claude", "dev", "skills"], "featured": True,
     "download_url": "https://example.com/downloads/claude-dev", "views": 520, "downloads": 280},
    {"title": "Agente de IA para Atendimento", "cat_slug": "ferramentas-ia", "type": "paid", "price": 297.0,
     "short_description": "Agente de IA completo para atendimento e suporte automatizado.",
     "description": "Solução completa de agente de IA para atendimento ao cliente 24/7. Integração com WhatsApp, base de conhecimento e escalonamento humano inteligente.",
     "thumbnail": IMG["aichat"], "tags": ["agente", "atendimento", "ia"], "featured": True,
     "checkout_url": "https://kiwify.com.br/checkout/agente-ia", "views": 265, "downloads": 0},
    {"title": "Ebook — Automação de Negócios com IA", "cat_slug": "cursos-ebooks", "type": "free", "price": 0.0,
     "short_description": "Guia gratuito para automatizar processos usando inteligência artificial.",
     "description": "Ebook completo com estratégias práticas para automatizar seu negócio com IA. Casos reais, ferramentas recomendadas e passo a passo de implementação.",
     "thumbnail": IMG["book"], "tags": ["ebook", "automacao", "gratis"], "featured": False,
     "download_url": "https://example.com/downloads/ebook-automacao", "views": 730, "downloads": 495},
    {"title": "Workflow n8n — Integração Total", "cat_slug": "automacoes", "type": "paid", "price": 127.0,
     "short_description": "Workflows n8n prontos para integrar suas ferramentas favoritas.",
     "description": "Biblioteca de workflows n8n prontos para integrar CRM, e-mail, planilhas, WhatsApp e IA. Copie, cole e automatize.",
     "thumbnail": IMG["workflow"], "tags": ["n8n", "integracao", "workflow"], "featured": False,
     "checkout_url": "https://kiwify.com.br/checkout/n8n-workflows", "views": 190, "downloads": 0},
    {"title": "Kit de Cursores & UI Neon", "cat_slug": "templates", "type": "paid", "price": 47.0,
     "short_description": "Componentes UI e cursores animados com estética neon.",
     "description": "Kit de componentes de interface com estética tech neon: botões, cards, cursores animados e microinterações prontas para seu projeto.",
     "thumbnail": IMG["neon"], "tags": ["ui", "design", "neon"], "featured": False,
     "checkout_url": "https://kiwify.com.br/checkout/ui-neon", "views": 120, "downloads": 0},
    {"title": "Guia de Segurança Digital", "cat_slug": "cursos-ebooks", "type": "free", "price": 0.0,
     "short_description": "Manual gratuito de boas práticas de segurança e privacidade.",
     "description": "Guia gratuito com boas práticas de segurança digital, proteção de dados e privacidade para profissionais e empresas.",
     "thumbnail": IMG["cyber"], "tags": ["seguranca", "guia", "gratis"], "featured": False,
     "download_url": "https://example.com/downloads/guia-seguranca", "views": 410, "downloads": 230},
    {"title": "Scraper Inteligente com IA", "cat_slug": "automacoes", "type": "paid", "price": 167.0,
     "short_description": "Ferramenta de scraping com processamento inteligente de dados.",
     "description": "Solução de web scraping potencializada por IA para coletar, estruturar e analisar dados automaticamente. Inclui código e documentação.",
     "thumbnail": IMG["matrix"], "tags": ["scraper", "dados", "ia"], "featured": False,
     "checkout_url": "https://kiwify.com.br/checkout/scraper-ia", "views": 155, "downloads": 0},
]

SEED_SKILLS = [
    {"title": "Refatorar Código", "category": "Desenvolvimento",
     "description": "Peça ao Claude para refatorar mantendo comportamento e melhorando legibilidade.",
     "command": "Refatore este código mantendo o comportamento idêntico. Melhore legibilidade, nomeie variáveis com clareza e adicione tipos onde fizer sentido:\n\n[cole seu código]",
     "tags": ["dev", "refactor"]},
    {"title": "Gerar Testes Unitários", "category": "Desenvolvimento",
     "description": "Crie testes cobrindo casos felizes e de borda.",
     "command": "Gere testes unitários completos para o código abaixo, cobrindo casos de sucesso, erro e borda. Use a biblioteca de testes idiomática da linguagem:\n\n[cole seu código]",
     "tags": ["dev", "testes"]},
    {"title": "Copywriting de Anúncio", "category": "Marketing",
     "description": "Gere variações de copy persuasiva para anúncios.",
     "command": "Escreva 5 variações de copy persuasiva para um anúncio do produto [PRODUTO], público [PÚBLICO], destacando o benefício [BENEFÍCIO]. Tom: [TOM].",
     "tags": ["marketing", "copy"]},
    {"title": "Resumir Documento", "category": "Produtividade",
     "description": "Extraia os pontos-chave de textos longos.",
     "command": "Resuma o texto abaixo em bullet points objetivos, destacando decisões, prazos e responsáveis:\n\n[cole o texto]",
     "tags": ["produtividade", "resumo"]},
    {"title": "Analisar Dados de Planilha", "category": "Dados",
     "description": "Interprete dados e gere insights acionáveis.",
     "command": "Analise os dados abaixo e liste 5 insights acionáveis, tendências e anomalias. Sugira próximos passos:\n\n[cole os dados]",
     "tags": ["dados", "analise"]},
    {"title": "Criar Plano de Conteúdo", "category": "Marketing",
     "description": "Monte um calendário editorial estratégico.",
     "command": "Crie um plano de conteúdo de 30 dias para [NICHO] no [CANAL], com temas, formatos e CTAs alinhados ao objetivo de [OBJETIVO].",
     "tags": ["marketing", "conteudo"]},
    {"title": "Revisar Contrato", "category": "Negócios",
     "description": "Identifique cláusulas de risco em contratos.",
     "command": "Revise o contrato abaixo e aponte cláusulas de risco, ambiguidades e pontos de atenção. Sugira melhorias em linguagem clara:\n\n[cole o contrato]",
     "tags": ["negocios", "juridico"]},
    {"title": "Documentar API", "category": "Desenvolvimento",
     "description": "Gere documentação clara de endpoints.",
     "command": "Gere documentação clara em formato Markdown para os endpoints abaixo, incluindo parâmetros, exemplos de request/response e códigos de erro:\n\n[cole os endpoints]",
     "tags": ["dev", "docs"]},
    {"title": "Diagnóstico de Bug", "category": "Desenvolvimento", "kind": "Análise", "level": "Intermediário",
     "description": "Investigue uma falha com hipóteses, evidências e um plano de correção.",
     "command": "Atue como um engenheiro de software sênior. Investigue o problema abaixo.\n\nContexto: [CONTEXTO]\nComportamento esperado: [ESPERADO]\nComportamento atual/erro: [ERRO]\nCódigo ou logs: [COLE AQUI]\n\nEntregue: 1) causas mais prováveis, 2) como validar cada hipótese, 3) correção mínima recomendada e 4) testes de regressão.",
     "tags": ["dev", "debug", "qualidade"]},
    {"title": "Planejar Feature", "category": "Desenvolvimento", "kind": "Planejamento", "level": "Intermediário",
     "description": "Transforme uma ideia em escopo técnico, etapas e critérios de aceite.",
     "command": "Converta esta solicitação em um plano de implementação: [IDEIA]\n\nConsidere o contexto técnico: [STACK/RESTRIÇÕES].\nEstruture em objetivo, escopo, itens fora de escopo, dependências, etapas incrementais, riscos e critérios de aceite verificáveis.",
     "tags": ["dev", "produto", "planejamento"]},
    {"title": "Revisão de Pull Request", "category": "Desenvolvimento", "kind": "Revisão", "level": "Avançado",
     "description": "Faça uma revisão objetiva com foco em bugs, segurança e manutenção.",
     "command": "Revise a alteração abaixo como um maintainer experiente. Priorize bugs, vulnerabilidades, regressões, desempenho e legibilidade.\n\n[COLE O DIFF OU CÓDIGO]\n\nPara cada achado, informe severidade, arquivo/trecho, impacto e sugestão concreta. Se não houver bloqueios, liste riscos residuais e testes recomendados.",
     "tags": ["dev", "code-review", "segurança"]},
    {"title": "SQL para Análise", "category": "Dados", "kind": "Geração", "level": "Intermediário",
     "description": "Crie uma consulta segura e explique como ela responde à pergunta de negócio.",
     "command": "Crie uma consulta SQL para responder: [PERGUNTA DE NEGÓCIO].\n\nEsquema/tabelas disponíveis: [ESQUEMA].\nBanco: [POSTGRES/MYSQL/etc.].\nInclua a query comentada, premissas, cuidados com dados nulos e uma sugestão de índice apenas se necessário.",
     "tags": ["dados", "sql", "analise"]},
    {"title": "Dashboard de Métricas", "category": "Dados", "kind": "Planejamento", "level": "Intermediário",
     "description": "Defina métricas, visuais e alertas que orientam decisões.",
     "command": "Desenhe um dashboard para o objetivo: [OBJETIVO].\nPúblico: [QUEM USA]. Fontes de dados: [FONTES].\n\nProponha KPIs com fórmula e frequência, gráficos adequados, segmentações, metas, alertas e perguntas que o dashboard deve responder. Evite métricas de vaidade.",
     "tags": ["dados", "kpi", "dashboard"]},
    {"title": "Plano de Lançamento", "category": "Marketing", "kind": "Planejamento", "level": "Intermediário",
     "description": "Estruture um lançamento com mensagens, canais e calendário de execução.",
     "command": "Crie um plano de lançamento para [PRODUTO].\nPúblico: [PÚBLICO]. Oferta: [OFERTA]. Meta: [META]. Canais: [CANAIS].\n\nOrganize pré-lançamento, lançamento e pós-lançamento em um calendário. Inclua mensagem central, CTAs, ativos necessários, métricas e riscos.",
     "tags": ["marketing", "lancamento", "estrategia"]},
    {"title": "Persona Baseada em Evidências", "category": "Marketing", "kind": "Análise", "level": "Iniciante",
     "description": "Consolide pesquisa de público em uma persona útil para comunicação.",
     "command": "Com base nas evidências abaixo, crie uma persona acionável para [PRODUTO/MARCA].\n\nEvidências: [PESQUISAS, ENTREVISTAS, COMENTÁRIOS]\n\nSepare fatos de hipóteses. Inclua tarefas que ela quer realizar, dores, objeções, linguagem, gatilhos de decisão e mensagens a testar.",
     "tags": ["marketing", "persona", "pesquisa"]},
    {"title": "Roteiro de Reels", "category": "Marketing", "kind": "Criação", "level": "Iniciante",
     "description": "Crie roteiros curtos com gancho, valor e chamada para ação.",
     "command": "Escreva 5 roteiros para Reels sobre [TEMA], para [PÚBLICO], com objetivo de [OBJETIVO].\nCada roteiro deve ter: gancho de até 2 segundos, falas/cenas em até 45 segundos, texto na tela, legenda e CTA. Tom: [TOM].",
     "tags": ["marketing", "reels", "conteudo"]},
    {"title": "Briefing Criativo", "category": "Marketing", "kind": "Criação", "level": "Iniciante",
     "description": "Converta uma demanda vaga em um briefing claro para criação.",
     "command": "Monte um briefing criativo para [PEÇA/CAMPANHA].\nContexto: [CONTEXTO]. Público: [PÚBLICO]. Objetivo: [OBJETIVO].\nDefina mensagem, promessa, mandatories, tom, referências de direção, entregáveis, formatos, cronograma e critérios de aprovação.",
     "tags": ["marketing", "briefing", "marca"]},
    {"title": "Proposta Comercial", "category": "Vendas", "kind": "Criação", "level": "Intermediário",
     "description": "Monte uma proposta centrada no problema e no valor entregue.",
     "command": "Crie uma proposta comercial para [CLIENTE] oferecer [SOLUÇÃO].\nProblema: [DOR]. Resultado desejado: [RESULTADO]. Escopo: [ESCOPO]. Investimento: [VALOR].\n\nEscreva em linguagem objetiva: contexto, solução, entregáveis, cronograma, investimento, diferenciais, próximos passos e campos que precisam de validação.",
     "tags": ["vendas", "proposta", "negociacao"]},
    {"title": "Qualificar Lead", "category": "Vendas", "kind": "Análise", "level": "Intermediário",
     "description": "Prepare perguntas de descoberta e uma recomendação de próximo passo.",
     "command": "Crie um roteiro de qualificação para o lead abaixo.\nEmpresa/perfil: [PERFIL]. Solução: [SOLUÇÃO].\n\nUse perguntas abertas para identificar problema, impacto, processo de decisão, urgência e orçamento. Ao final, defina sinais de fit, red flags e o próximo passo recomendado.",
     "tags": ["vendas", "lead", "discovery"]},
    {"title": "Sequência de Follow-up", "category": "Vendas", "kind": "Criação", "level": "Iniciante",
     "description": "Escreva contatos de acompanhamento que acrescentam valor sem pressionar.",
     "command": "Crie uma sequência de 4 follow-ups para [TIPO DE LEAD] após [CONTEXTO].\nCanal: [EMAIL/WHATSAPP/LINKEDIN].\nCada mensagem deve ter um objetivo, assunto (se email), texto curto, valor novo e CTA leve. Tom: [TOM].",
     "tags": ["vendas", "follow-up", "copy"]},
    {"title": "Plano Estratégico de 90 Dias", "category": "Negócios", "kind": "Planejamento", "level": "Avançado",
     "description": "Priorize iniciativas em um plano realista de execução trimestral.",
     "command": "Crie um plano de 90 dias para alcançar [OBJETIVO].\nContexto atual: [CONTEXTO]. Recursos/equipe: [RECURSOS]. Restrições: [RESTRIÇÕES].\n\nDefina 3 prioridades, indicadores de resultado, marcos quinzenais, donos, riscos e uma cadência de revisão. Mostre claramente o que não será priorizado.",
     "tags": ["negocios", "estrategia", "execucao"]},
    {"title": "Análise de Concorrentes", "category": "Negócios", "kind": "Análise", "level": "Intermediário",
     "description": "Compare alternativas do mercado e encontre espaço de posicionamento.",
     "command": "Analise estes concorrentes/alternativas: [LISTA].\nNosso produto: [PRODUTO]. Público: [PÚBLICO].\nMonte uma comparação de proposta de valor, público, mensagem, preço percebido, pontos fortes/fracos e oportunidades de diferenciação. Marque inferências que precisem de pesquisa adicional.",
     "tags": ["negocios", "concorrencia", "posicionamento"]},
    {"title": "SOP de Processo", "category": "Operações", "kind": "Documentação", "level": "Intermediário",
     "description": "Documente um processo repetível, simples de treinar e auditar.",
     "command": "Documente um procedimento operacional padrão para [PROCESSO].\nPúblico: [QUEM EXECUTA]. Ferramentas: [FERRAMENTAS].\nInclua objetivo, gatilho, responsáveis, pré-requisitos, passos numerados, checklist de qualidade, exceções, SLA e histórico de revisão.",
     "tags": ["operacoes", "sop", "processos"]},
    {"title": "Checklist de Reunião", "category": "Produtividade", "kind": "Planejamento", "level": "Iniciante",
     "description": "Transforme reuniões em decisões, responsáveis e próximos passos.",
     "command": "Crie uma pauta e checklist para uma reunião sobre [TEMA].\nParticipantes: [PARTICIPANTES]. Objetivo: [OBJETIVO]. Duração: [DURAÇÃO].\nInclua preparação, agenda com tempos, decisões esperadas, modelo de ata e próximos passos com responsável e prazo.",
     "tags": ["produtividade", "reuniao", "gestao"]},
    {"title": "Priorizar Tarefas", "category": "Produtividade", "kind": "Análise", "level": "Iniciante",
     "description": "Organize uma lista de trabalho por impacto, urgência e esforço.",
     "command": "Priorize estas tarefas: [LISTA].\nObjetivo da semana: [OBJETIVO]. Restrições: [RESTRIÇÕES].\nClassifique por impacto, urgência e esforço; sugira o que fazer, delegar, agendar ou eliminar. Entregue uma sequência prática para os próximos 5 dias.",
     "tags": ["produtividade", "priorizacao", "foco"]},
    {"title": "Explicar para Iniciantes", "category": "Educação", "kind": "Explicação", "level": "Iniciante",
     "description": "Explique um tema complexo com analogias e exemplos progressivos.",
     "command": "Explique [TEMA] para uma pessoa iniciante que já sabe [CONHECIMENTO PRÉVIO].\nUse linguagem simples, uma analogia útil, exemplo prático, erros comuns e 3 perguntas rápidas para verificar entendimento. Evite simplificações incorretas.",
     "tags": ["educacao", "explicacao", "aprendizado"]},
    {"title": "Plano de Estudos", "category": "Educação", "kind": "Planejamento", "level": "Iniciante",
     "description": "Monte uma trilha de aprendizado com prática e revisões.",
     "command": "Monte um plano de estudos de [DURAÇÃO] para aprender [TEMA].\nNível atual: [NÍVEL]. Tempo disponível: [HORAS/SEMANA]. Objetivo final: [OBJETIVO].\nOrganize por semanas com conceitos, prática deliberada, projeto, revisão e critérios para avançar.",
     "tags": ["educacao", "estudos", "planejamento"]},
    {"title": "E-mail Profissional", "category": "Comunicação", "kind": "Criação", "level": "Iniciante",
     "description": "Escreva um e-mail claro, respeitoso e orientado à ação.",
     "command": "Escreva um e-mail para [DESTINATÁRIO] sobre [ASSUNTO].\nContexto: [CONTEXTO]. Resultado desejado: [RESULTADO]. Tom: [TOM].\nCrie assunto e corpo conciso, com uma chamada para ação clara. Não invente fatos ou compromissos.",
     "tags": ["comunicacao", "email", "escrita"]},
    {"title": "Preparar Feedback", "category": "Comunicação", "kind": "Planejamento", "level": "Intermediário",
     "description": "Estruture uma conversa de feedback específica, humana e acionável.",
     "command": "Ajude a preparar um feedback para [PESSOA/FUNÇÃO].\nSituação observada: [FATOS]. Impacto: [IMPACTO]. Resultado desejado: [RESULTADO].\nMonte uma conversa usando contexto, comportamento, impacto e próximo passo. Inclua perguntas de escuta e evite atribuir intenções.",
     "tags": ["comunicacao", "feedback", "lideranca"]},
    {"title": "Planejar Fluxo de Automação", "category": "Automação", "kind": "Planejamento", "level": "Avançado",
     "description": "Desenhe um fluxo automatizado com gatilhos, exceções e observabilidade.",
     "command": "Desenhe uma automação para [PROCESSO].\nGatilho: [GATILHO]. Ferramentas: [FERRAMENTAS]. Dados de entrada: [DADOS].\nDescreva o fluxo passo a passo, validações, tratamento de erros, notificações, permissões, logs e como medir se a automação funciona.",
     "tags": ["automacao", "workflow", "processos"]},
    {"title": "Resposta de Suporte", "category": "Atendimento", "kind": "Criação", "level": "Iniciante",
     "description": "Crie uma resposta empática que resolve ou encaminha o pedido.",
     "command": "Escreva uma resposta de suporte para esta solicitação: [MENSAGEM DO CLIENTE].\nPolítica/contexto: [CONTEXTO].\nReconheça o problema, informe o que pode ser feito sem prometer o que não é possível, explique os próximos passos e encerre de forma acolhedora.",
     "tags": ["atendimento", "suporte", "cliente"]},
    {"title": "Plano de Projeto", "category": "Gestão", "kind": "Planejamento", "level": "Intermediário",
     "description": "Estruture entregas, responsáveis e riscos de um projeto.",
     "command": "Monte um plano para o projeto [PROJETO].\nObjetivo: [OBJETIVO]. Prazo: [PRAZO]. Equipe: [EQUIPE].\nQuebre em entregas, marcos, dependências, responsáveis, riscos, plano de comunicação e indicadores de progresso. Destaque premissas que precisam ser confirmadas.",
     "tags": ["gestao", "projeto", "planejamento"]},
]

SEED_COMMUNITY = [
    {"name": "Grupo VIP no WhatsApp", "platform": "whatsapp", "url": "https://chat.whatsapp.com/exemplo",
     "description": "Comunidade exclusiva com novidades, drops e suporte.", "icon": "message-circle"},
    {"name": "Canal no Telegram", "platform": "telegram", "url": "https://t.me/exemplo",
     "description": "Avisos rápidos, lançamentos e conteúdos gratuitos.", "icon": "send"},
    {"name": "Comunidade no Discord", "platform": "discord", "url": "https://discord.gg/exemplo",
     "description": "Troque ideias, tire dúvidas e participe de eventos ao vivo.", "icon": "gamepad-2"},
    {"name": "Perfil no Instagram", "platform": "instagram", "url": "https://instagram.com/exemplo",
     "description": "Bastidores, dicas e novidades da marca.", "icon": "instagram"},
    {"name": "Canal no YouTube", "platform": "youtube", "url": "https://youtube.com/@exemplo",
     "description": "Tutoriais, reviews e aulas completas.", "icon": "youtube"},
]

SEED_FAQS = [
    {"question": "Como acesso os produtos gratuitos?", "category": "Acesso",
     "answer": "Basta criar sua conta gratuita, acessar a página do produto e preencher o formulário. O link de download é liberado na hora e também fica salvo em Minha Conta."},
    {"question": "Como funciona a compra de produtos pagos?", "category": "Pagamento",
     "answer": "Ao clicar em comprar, você é redirecionado para nosso checkout seguro externo. Após a confirmação do pagamento, o acesso é liberado e registrado no seu histórico."},
    {"question": "Quais formas de pagamento são aceitas?", "category": "Pagamento",
     "answer": "Aceitamos cartão de crédito, Pix e boleto através da nossa plataforma de checkout. As opções aparecem na tela de pagamento."},
    {"question": "Posso acessar meus produtos depois?", "category": "Acesso",
     "answer": "Sim! Todos os seus downloads e compras ficam salvos permanentemente na área Minha Conta, acessível a qualquer momento."},
    {"question": "O que são skills?", "category": "Recursos",
     "answer": "São comandos e prompts avançados prontos para usar com o Claude. Você pode copiar cada comando com um clique e usá-lo diretamente na sua IA."},
    {"question": "Como entro em contato com o suporte?", "category": "Suporte",
     "answer": "Você pode falar conosco pelos canais da Comunidade (WhatsApp, Telegram, Discord) ou usar o assistente de IA disponível no canto da tela."},
    {"question": "Vocês oferecem reembolso?", "category": "Pagamento",
     "answer": "Sim, produtos pagos possuem garantia conforme descrito na página de checkout. Entre em contato com o suporte para solicitar."},
]


# Árvore operacional do SENTIENT-AI. Estes registros pertencem ao hub administrativo
# e são independentes do catálogo público de produtos.
SEED_AUTOMATION_NODES = [
    {
        "id": "sentient-root",
        "name": "SENTIENT-AI",
        "type": "root",
        "icon": "orbit",
        "category": "Estrutural",
        "color": "#94A3B8",
        "status": "active",
        "parent_id": None,
        "order": 0,
        "meta": {
            "description": "Centro de comando para automações, agentes e conexões inteligentes.",
        },
    },
    {
        "id": "operations-hub",
        "name": "Centro de Operações",
        "type": "hub",
        "icon": "network",
        "category": "Estrutural",
        "color": "#94A3B8",
        "status": "active",
        "parent_id": "sentient-root",
        "order": 0,
        "meta": {
            "description": "Hub central que coordena os fluxos ativos da operação.",
        },
    },
    {
        "id": "communication",
        "name": "Comunicação",
        "type": "category",
        "icon": "messages-square",
        "category": "Comunicação",
        "color": "#22D3EE",
        "status": "active",
        "parent_id": "operations-hub",
        "order": 0,
        "meta": {
            "description": "Entradas, saídas e notificações de relacionamento.",
        },
    },
    {
        "id": "lead-qualification",
        "name": "Qualificação de leads",
        "type": "agent",
        "icon": "sparkles",
        "category": "Comunicação",
        "color": "#22D3EE",
        "status": "active",
        "parent_id": "communication",
        "order": 0,
        "model": "Claude Sonnet",
        "provider": "Anthropic",
        "meta": {
            "description": "Classifica novos leads e encaminha cada conversa para a próxima etapa.",
        },
    },
    {
        "id": "whatsapp-gateway",
        "name": "WhatsApp Gateway",
        "type": "tool",
        "icon": "message-circle",
        "category": "Comunicação",
        "color": "#22D3EE",
        "status": "active",
        "parent_id": "communication",
        "order": 1,
        "provider": "Twilio API",
        "meta": {
            "description": "Canal de mensagens para atendimento e notificações.",
        },
    },
    {
        "id": "automation",
        "name": "Automação",
        "type": "category",
        "icon": "workflow",
        "category": "Automação",
        "color": "#FB923C",
        "status": "active",
        "parent_id": "operations-hub",
        "order": 1,
        "meta": {
            "description": "Orquestração de tarefas e rotinas recorrentes.",
        },
    },
    {
        "id": "content-pipeline",
        "name": "Pipeline de conteúdo",
        "type": "agent",
        "icon": "bot",
        "category": "Automação",
        "color": "#FB923C",
        "status": "waiting_approval",
        "parent_id": "automation",
        "order": 0,
        "model": "GPT-4.1",
        "provider": "OpenAI",
        "meta": {
            "description": "Gera, revisa e prepara conteúdo para aprovação antes da publicação.",
        },
    },
    {
        "id": "crm-sync",
        "name": "Sincronização CRM",
        "type": "agent",
        "icon": "refresh-cw",
        "category": "Automação",
        "color": "#FB923C",
        "status": "idle",
        "parent_id": "automation",
        "order": 1,
        "model": "Claude Haiku",
        "provider": "Anthropic",
        "meta": {
            "description": "Mantém contatos e eventos sincronizados com o CRM.",
        },
    },
    {
        "id": "intelligence",
        "name": "IA / Agentes",
        "type": "category",
        "icon": "brain",
        "category": "IA",
        "color": "#A78BFA",
        "status": "active",
        "parent_id": "operations-hub",
        "order": 2,
        "meta": {
            "description": "Agentes inteligentes e camadas de decisão da operação.",
        },
    },
    {
        "id": "support-agent",
        "name": "Agente de suporte",
        "type": "agent",
        "icon": "headphones",
        "category": "IA",
        "color": "#A78BFA",
        "status": "active",
        "parent_id": "intelligence",
        "order": 0,
        "model": "Claude Sonnet",
        "provider": "Anthropic",
        "meta": {
            "description": "Responde dúvidas e sugere recursos do catálogo em tempo real.",
        },
    },
    {
        "id": "data",
        "name": "Dados",
        "type": "category",
        "icon": "database",
        "category": "Dados",
        "color": "#2DD4BF",
        "status": "active",
        "parent_id": "operations-hub",
        "order": 3,
        "meta": {
            "description": "Persistência, consultas e observabilidade do ecossistema.",
        },
    },
    {
        "id": "analytics-agent",
        "name": "Análise de métricas",
        "type": "agent",
        "icon": "chart-no-axes-combined",
        "category": "Dados",
        "color": "#2DD4BF",
        "status": "active",
        "parent_id": "data",
        "order": 0,
        "model": "GPT-4.1 mini",
        "provider": "OpenAI",
        "meta": {
            "description": "Consolida métricas e sinaliza desvios importantes para o time.",
        },
    },
    {
        "id": "mongo-database",
        "name": "MongoDB",
        "type": "tool",
        "icon": "database-zap",
        "category": "Dados",
        "color": "#2DD4BF",
        "status": "active",
        "parent_id": "data",
        "order": 1,
        "provider": "MongoDB",
        "meta": {
            "description": "Fonte persistida de usuários, catálogo, automações e execuções.",
        },
    },
]

SEED_AUTOMATION_EXECUTIONS = [
    {"node_id": "lead-qualification", "status": "success", "duration_seconds": 2.8, "minutes_ago": 14},
    {"node_id": "support-agent", "status": "success", "duration_seconds": 1.9, "minutes_ago": 41},
    {"node_id": "analytics-agent", "status": "success", "duration_seconds": 4.2, "minutes_ago": 86},
    {"node_id": "content-pipeline", "status": "waiting_approval", "duration_seconds": 3.6, "minutes_ago": 142},
    {"node_id": "lead-qualification", "status": "success", "duration_seconds": 2.4, "minutes_ago": 231},
    {"node_id": "crm-sync", "status": "error", "duration_seconds": 7.1, "minutes_ago": 318},
]

TECH_STACK_NODES = [
    {"id": "stack-react", "name": "React 19", "icon": "atom", "color": "#61DAFB"},
    {"id": "stack-fastapi", "name": "FastAPI", "icon": "server", "color": "#2DD4BF"},
    {"id": "stack-mongodb", "name": "MongoDB", "icon": "database", "color": "#22C55E"},
    {"id": "stack-n8n", "name": "n8n", "icon": "workflow", "color": "#FB923C"},
]

TECH_STACK_SAVINGS_MONTH_CENTS = 184500
TECH_STACK_CONNECTIONS_ACTIVE = 8
TECH_STACK_AUTOMATIONS_ACTIVE = 4
TECH_STACK_EXECUTIONS_24H = 128
